=== Zyrakia/neuw/neuw.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string",
			"description": "A descriptive name of the template."
		},
		"description": {
			"type": "string",
			"description": "A concise description of the template, further detailing what type of project it can be used to bootstrap."
		},
		"variables": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"description": "The name of the variable, this should be a readable and concise name."
					},
					"description": {
						"type": "string",
						"description": "The concise description of how the variable is used within the template."
					},
					"identifier": {
						"type": "string",
						"minLength": 1,
						"pattern": "^[A-Za-z]+$",
						"description": "The identifier that this variable will be referenced by in evaluated content."
					},
					"default": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"type": "number"
							},
							{
								"type": "boolean"
							}
						],
						"description": "The default value of this variable."
					},
					"required": {
						"type": "boolean",
						"description": "Whether the variable is required to be set."
					},
					"type": {
						"oneOf": [
							{
								"type": "string",
								"enum": ["string", "boolean", "double", "int", "any"]
							},
							{
								"type": "object",
								"additionalProperties": true,
								"properties": {
									"base": {
										"type": "string",
										"enum": ["string", "boolean", "double", "int"]
									}
								},
								"description": "A refined base type that can add additional rules."
							}
						],
						"description": "The type of the variable, can be a base type or a refined base type."
					}
				},
				"required": ["name", "identifier", "type"]
			},
			"description": "The variables that this template defines to customize bootstrapping."
		},
		"commands": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"stage": {
						"type": "string",
						"enum": ["post-write", "pre-write"],
						"description": "The stage at which this command will run.",
						"enumDesc": "A command can run before the structure of the template is written, or after. Commands will always run after variables have been evaluated."
					},
					"condition": {
						"type": "string",
						"description": "The condition that determines whether this command will execute. This property is optional, but if defined, it should evaluate to a boolean value, any other value will mean the command will automatically be ignored."
					},
					"command": {
						"type": "string",
						"description": "The actual command that will be run."
					}
				},
				"required": ["stage", "command"]
			},
			"description": "The commands executed in different stages of the building of this template."
		},
		"structure": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"description": "The name of the structure item."
					},
					"content": {
						"oneOf": [
							{
								"type": "string",
								"description": "The content of this file structure item."
							},
							{
								"type": "array",
								"items": {
									"$ref": "#/properties/structure/items",
									"type": "string"
								},
								"description": "The children of this directory structure item."
							}
						],
						"description": "Either string content (indicating that this item is a file), or an array of children items (indicating that this item is a directory)."
					},
					"condition": {
						"type": "string",
						"description": "The condition that determines whether this structure item will be written. This property is optional, but if defined, it should evaluate to a boolean value, any other value will mean the structure item will automatically be ignored."
					}
				},
				"dependencies": {
					"content": {
						"not": {
							"required": ["children"]
						}
					}
				},
				"required": ["name"]
			},
			"description": "The files and folders that make up this template."
		}
	},
	"required": ["name", "structure"],
	"title": "Neuw Template",
	"description": "Details a template that can be used to bootstrap a project via Neuw."
}

=== Zyrakia/neuw/test-templates/typescript-node-starter.json
{
	"name": "Typescript Node Starter",
	"variables": [
		{
			"name": "Project Name",
			"description": "The name of your project",
			"identifier": "projectName",
			"required": true,
			"type": { "base": "string", "rules": [{ "name": "string-constrained", "min": 1 }] }
		},
		{
			"name": "Project Description",
			"description": "The short description of your project",
			"identifier": "projectDescription",
			"default": "",
			"type": { "base": "string" }
		},
		{
			"name": "Use Git",
			"description": "Whether Git should be enabled after the template is built.",
			"identifier": "useGit",
			"default": false,
			"type": "boolean"
		}
	],
	"commands": [
		{
			"stage": "post-write",
			"condition": "useGit === true",
			"command": "git init"
		},
		{
			"stage": "post-write",
			"condition": "useGit === true",
			"command": "git add ."
		},
		{
			"stage": "post-write",
			"command": "npm install"
		}
	],
	"structure": [
		{
			"name": "README.md",
			"content": "# {{ projectName }}"
		},
		{
			"name": "package.json",
			"content": "{\n    \"name\": \"{{ projectName }}\",\n    \"version\": \"1.0.0\",\n    \"description\": \"{{ projectDescription }}\",\n    \"license\": \"MIT\",\n    \"scripts\": {\n        \"start\": \"node ./dist/index.js\",\n        \"build\": \"tsc\"\n    },\n    \"dependencies\": {},\n    \"devDependencies\": {\n        \"@types/node\": \"^12.0.2\",\n        \"typescript\": \"^3.4.5\"\n    }\n}\n"
		},
		{
			"name": "tsconfig.json",
			"content": "{\n    \"compilerOptions\": {\n        \"module\": \"commonjs\",\n        \"esModuleInterop\": true,\n        \"target\": \"es6\",\n        \"noImplicitAny\": true,\n        \"moduleResolution\": \"node\",\n        \"sourceMap\": true,\n        \"outDir\": \"dist\",\n        \"baseUrl\": \".\",\n        \"paths\": {\n            \"*\": [\n                \"node_modules/*\",\n                \"src/types/*\"\n            ]\n        }\n    },\n    \"include\": [\n        \"src/**/*\"\n    ]\n}"
		},
		{
			"name": ".gitignore",
			"condition": "useGit",
			"content": "### Node ###\n# Logs\nlogs\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\nlerna-debug.log*\n.pnpm-debug.log*\n\n# Diagnostic reports (https://nodejs.org/api/report.html)\nreport.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json\n\n# Runtime data\npids\n*.pid\n*.seed\n*.pid.lock\n\n# Directory for instrumented libs generated by jscoverage/JSCover\nlib-cov\n\n# Coverage directory used by tools like istanbul\ncoverage\n*.lcov\n\n# nyc test coverage\n.nyc_output\n\n# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)\n.grunt\n\n# Bower dependency directory (https://bower.io/)\nbower_components\n\n# node-waf configuration\n.lock-wscript\n\n# Compiled binary addons (https://nodejs.org/api/addons.html)\nbuild/Release\n\n# Dependency directories\nnode_modules/\njspm_packages/\n\n# Snowpack dependency directory (https://snowpack.dev/)\nweb_modules/\n\n# TypeScript cache\n*.tsbuildinfo\n\n# Optional npm cache directory\n.npm\n\n# Optional eslint cache\n.eslintcache\n\n# Optional stylelint cache\n.stylelintcache\n\n# Microbundle cache\n.rpt2_cache/\n.rts2_cache_cjs/\n.rts2_cache_es/\n.rts2_cache_umd/\n\n# Optional REPL history\n.node_repl_history\n\n# Output of 'npm pack'\n*.tgz\n\n# Yarn Integrity file\n.yarn-integrity\n\n# dotenv environment variable files\n.env\n.env.development.local\n.env.test.local\n.env.production.local\n.env.local\n\n# parcel-bundler cache (https://parceljs.org/)\n.cache\n.parcel-cache\n\n# Next.js build output\n.next\nout\n\n# Nuxt.js build / generate output\n.nuxt\ndist\n\n# Gatsby files\n.cache/\n# Comment in the public line in if your project uses Gatsby and not Next.js\n# https://nextjs.org/blog/next-9-1#public-directory-support\n# public\n\n# vuepress build output\n.vuepress/dist\n\n# vuepress v2.x temp and cache directory\n.temp\n\n# Docusaurus cache and generated files\n.docusaurus\n\n# Serverless directories\n.serverless/\n\n# FuseBox cache\n.fusebox/\n\n# DynamoDB Local files\n.dynamodb/\n\n# TernJS port file\n.tern-port\n\n# Stores VSCode versions used for testing VSCode extensions\n.vscode-test\n\n# yarn v2\n.yarn/cache\n.yarn/unplugged\n.yarn/build-state.yml\n.yarn/install-state.gz\n.pnp.*\n\n### Node Patch ###\n# Serverless Webpack directories\n.webpack/\n\n# Optional stylelint cache\n\n# SvelteKit build / generate output\n.svelte-kit"
		},
		{
			"name": "src",
			"children": [
				{
					"name": "index.ts",
					"content": "console.log('Hello World!');"
				}
			]
		}
	]
}

=== Zyrakia/neuw/test-templates/typescript-node-starter.neuw.json
{
	"name": "Typescript Node Starter",
	"variables": [
		{
			"name": "Project Name",
			"description": "The name of your project",
			"identifier": "projectName",
			"required": true,
			"type": {
				"base": "string",
				"constrained": {
					"min": 1
				}
			}
		},
		{
			"name": "Project Description",
			"description": "The short description of your project",
			"identifier": "projectDescription",
			"default": "",
			"type": "string"
		},
		{
			"name": "Use Git",
			"description": "Whether Git should be enabled after the template is built.",
			"identifier": "useGit",
			"default": false,
			"type": "boolean"
		},
		{
			"name": "Author Name",
			"description": "The name of the author of the project",
			"required": true,
			"identifier": "authorName",
			"type": "string"
		},
		{
			"name": "License",
			"description": "The license of the project",
			"default": "MIT",
			"identifier": "license",
			"type": {
				"base": "string",
				"enum": ["MIT", "Apache-2.0", "GPL-3.0"]
			}
		}
	],
	"commands": [
		{
			"stage": "post-write",
			"condition": "useGit === true",
			"command": "git init"
		},
		{
			"stage": "post-write",
			"condition": "useGit === true",
			"command": "git add ."
		},
		{
			"stage": "post-write",
			"command": "npm install"
		}
	],
	"structure": [
		{
			"name": "README.md",
			"content": "# {{ projectName }}"
		},
		{
			"name": "LICENSE",
			"content": "{{ license === 'MIT' ? `Copyright ${new Date().getFullYear()} ${authorName}\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.` : license === 'Apache-2.0' ? `Copyright ${new Date().getFullYear()} ${authorName}\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.` : `Copyright (C) ${new Date().getFullYear()} ${authorName}\n\nThis program is free software: you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see <https://www.gnu.org/licenses/>.` }}"
		},
		{
			"name": "package.json",
			"content": "{\n    \"name\": \"{{ projectName }}\",\n    \"version\": \"1.0.0\",\n    \"description\": \"{{ projectDescription }}\",\n    \"author\": \"{{ authorName }}\",\n    \"license\": \"MIT\",\n    \"scripts\": {\n        \"start\": \"node ./dist/index.js\",\n        \"build\": \"tsc\"\n    },\n    \"dependencies\": {},\n    \"devDependencies\": {\n        \"@types/node\": \"^12.0.2\",\n        \"typescript\": \"^3.4.5\"\n    }\n}\n"
		},
		{
			"name": "tsconfig.json",
			"content": "{\n    \"compilerOptions\": {\n        \"module\": \"commonjs\",\n        \"esModuleInterop\": true,\n        \"target\": \"es6\",\n        \"noImplicitAny\": true,\n        \"moduleResolution\": \"node\",\n        \"sourceMap\": true,\n        \"outDir\": \"dist\",\n        \"baseUrl\": \".\",\n        \"paths\": {\n            \"*\": [\n                \"node_modules/*\",\n                \"src/types/*\"\n            ]\n        }\n    },\n    \"include\": [\n        \"src/**/*\"\n    ]\n}"
		},
		{
			"name": ".gitignore",
			"condition": "useGit",
			"content": "### Node ###\n# Logs\nlogs\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\nlerna-debug.log*\n.pnpm-debug.log*\n\n# Diagnostic reports (https://nodejs.org/api/report.html)\nreport.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json\n\n# Runtime data\npids\n*.pid\n*.seed\n*.pid.lock\n\n# Directory for instrumented libs generated by jscoverage/JSCover\nlib-cov\n\n# Coverage directory used by tools like istanbul\ncoverage\n*.lcov\n\n# nyc test coverage\n.nyc_output\n\n# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)\n.grunt\n\n# Bower dependency directory (https://bower.io/)\nbower_components\n\n# node-waf configuration\n.lock-wscript\n\n# Compiled binary addons (https://nodejs.org/api/addons.html)\nbuild/Release\n\n# Dependency directories\nnode_modules/\njspm_packages/\n\n# Snowpack dependency directory (https://snowpack.dev/)\nweb_modules/\n\n# TypeScript cache\n*.tsbuildinfo\n\n# Optional npm cache directory\n.npm\n\n# Optional eslint cache\n.eslintcache\n\n# Optional stylelint cache\n.stylelintcache\n\n# Microbundle cache\n.rpt2_cache/\n.rts2_cache_cjs/\n.rts2_cache_es/\n.rts2_cache_umd/\n\n# Optional REPL history\n.node_repl_history\n\n# Output of 'npm pack'\n*.tgz\n\n# Yarn Integrity file\n.yarn-integrity\n\n# dotenv environment variable files\n.env\n.env.development.local\n.env.test.local\n.env.production.local\n.env.local\n\n# parcel-bundler cache (https://parceljs.org/)\n.cache\n.parcel-cache\n\n# Next.js build output\n.next\nout\n\n# Nuxt.js build / generate output\n.nuxt\ndist\n\n# Gatsby files\n.cache/\n# Comment in the public line in if your project uses Gatsby and not Next.js\n# https://nextjs.org/blog/next-9-1#public-directory-support\n# public\n\n# vuepress build output\n.vuepress/dist\n\n# vuepress v2.x temp and cache directory\n.temp\n\n# Docusaurus cache and generated files\n.docusaurus\n\n# Serverless directories\n.serverless/\n\n# FuseBox cache\n.fusebox/\n\n# DynamoDB Local files\n.dynamodb/\n\n# TernJS port file\n.tern-port\n\n# Stores VSCode versions used for testing VSCode extensions\n.vscode-test\n\n# yarn v2\n.yarn/cache\n.yarn/unplugged\n.yarn/build-state.yml\n.yarn/install-state.gz\n.pnp.*\n\n### Node Patch ###\n# Serverless Webpack directories\n.webpack/\n\n# Optional stylelint cache\n\n# SvelteKit build / generate output\n.svelte-kit"
		},
		{
			"name": "src",
			"content": []
		}
	]
}
